export interface Area {
  name: string
  slug: string
}

export interface City {
  name: string
  slug: string
  state: string
  areas: Area[]
}

export const CITIES: City[] = [
  {
    name: 'Mumbai',
    slug: 'mumbai',
    state: 'Maharashtra',
    areas: [
      { name: 'Andheri', slug: 'andheri' },
      { name: 'Bandra', slug: 'bandra' },
      { name: 'Borivali', slug: 'borivali' },
      { name: 'Dadar', slug: 'dadar' },
      { name: 'Goregaon', slug: 'goregaon' },
      { name: 'Juhu', slug: 'juhu' },
      { name: 'Kurla', slug: 'kurla' },
      { name: 'Lower Parel', slug: 'lower-parel' },
      { name: 'Malad', slug: 'malad' },
      { name: 'Mulund', slug: 'mulund' },
      { name: 'Navi Mumbai', slug: 'navi-mumbai' },
      { name: 'Powai', slug: 'powai' },
      { name: 'Thane', slug: 'thane' },
      { name: 'Versova', slug: 'versova' },
      { name: 'Vikhroli', slug: 'vikhroli' },
      { name: 'Worli', slug: 'worli' },
    ],
  },
  {
    name: 'Delhi',
    slug: 'delhi',
    state: 'Delhi',
    areas: [
      { name: 'Connaught Place', slug: 'connaught-place' },
      { name: 'Dwarka', slug: 'dwarka' },
      { name: 'Greater Kailash', slug: 'greater-kailash' },
      { name: 'Janakpuri', slug: 'janakpuri' },
      { name: 'Lajpat Nagar', slug: 'lajpat-nagar' },
      { name: 'Nehru Place', slug: 'nehru-place' },
      { name: 'Pitampura', slug: 'pitampura' },
      { name: 'Preet Vihar', slug: 'preet-vihar' },
      { name: 'Rohini', slug: 'rohini' },
      { name: 'Saket', slug: 'saket' },
      { name: 'Shahdara', slug: 'shahdara' },
      { name: 'South Extension', slug: 'south-extension' },
      { name: 'Vasant Kunj', slug: 'vasant-kunj' },
      { name: 'Noida', slug: 'noida' },
      { name: 'Gurgaon', slug: 'gurgaon' },
      { name: 'Faridabad', slug: 'faridabad' },
    ],
  },
  {
    name: 'Bangalore',
    slug: 'bangalore',
    state: 'Karnataka',
    areas: [
      { name: 'Bellandur', slug: 'bellandur' },
      { name: 'BTM Layout', slug: 'btm-layout' },
      { name: 'Electronic City', slug: 'electronic-city' },
      { name: 'Hebbal', slug: 'hebbal' },
      { name: 'HSR Layout', slug: 'hsr-layout' },
      { name: 'Indiranagar', slug: 'indiranagar' },
      { name: 'Jayanagar', slug: 'jayanagar' },
      { name: 'JP Nagar', slug: 'jp-nagar' },
      { name: 'Koramangala', slug: 'koramangala' },
      { name: 'Malleswaram', slug: 'malleswaram' },
      { name: 'Marathahalli', slug: 'marathahalli' },
      { name: 'Rajajinagar', slug: 'rajajinagar' },
      { name: 'Sarjapur Road', slug: 'sarjapur-road' },
      { name: 'Whitefield', slug: 'whitefield' },
      { name: 'Yelahanka', slug: 'yelahanka' },
      { name: 'Yeshwanthpur', slug: 'yeshwanthpur' },
    ],
  },
  {
    name: 'Hyderabad',
    slug: 'hyderabad',
    state: 'Telangana',
    areas: [
      { name: 'Ameerpet', slug: 'ameerpet' },
      { name: 'Banjara Hills', slug: 'banjara-hills' },
      { name: 'Charminar', slug: 'charminar' },
      { name: 'Gachibowli', slug: 'gachibowli' },
      { name: 'Hi-Tech City', slug: 'hitech-city' },
      { name: 'Jubilee Hills', slug: 'jubilee-hills' },
      { name: 'Kondapur', slug: 'kondapur' },
      { name: 'Kukatpally', slug: 'kukatpally' },
      { name: 'LB Nagar', slug: 'lb-nagar' },
      { name: 'Madhapur', slug: 'madhapur' },
      { name: 'Malkajgiri', slug: 'malkajgiri' },
      { name: 'Miyapur', slug: 'miyapur' },
      { name: 'Secunderabad', slug: 'secunderabad' },
      { name: 'Uppal', slug: 'uppal' },
    ],
  },
  {
    name: 'Chennai',
    slug: 'chennai',
    state: 'Tamil Nadu',
    areas: [
      { name: 'Adyar', slug: 'adyar' },
      { name: 'Anna Nagar', slug: 'anna-nagar' },
      { name: 'Chrompet', slug: 'chrompet' },
      { name: 'Guindy', slug: 'guindy' },
      { name: 'Kilpauk', slug: 'kilpauk' },
      { name: 'Kodambakkam', slug: 'kodambakkam' },
      { name: 'Mylapore', slug: 'mylapore' },
      { name: 'Nungambakkam', slug: 'nungambakkam' },
      { name: 'OMR', slug: 'omr' },
      { name: 'Perambur', slug: 'perambur' },
      { name: 'Porur', slug: 'porur' },
      { name: 'T Nagar', slug: 't-nagar' },
      { name: 'Tambaram', slug: 'tambaram' },
      { name: 'Velachery', slug: 'velachery' },
    ],
  },
  {
    name: 'Kolkata',
    slug: 'kolkata',
    state: 'West Bengal',
    areas: [
      { name: 'Ballygunge', slug: 'ballygunge' },
      { name: 'Behala', slug: 'behala' },
      { name: 'Dum Dum', slug: 'dum-dum' },
      { name: 'Howrah', slug: 'howrah' },
      { name: 'Jadavpur', slug: 'jadavpur' },
      { name: 'Lake Town', slug: 'lake-town' },
      { name: 'New Town', slug: 'new-town' },
      { name: 'Park Street', slug: 'park-street' },
      { name: 'Salt Lake', slug: 'salt-lake' },
      { name: 'Tollygunge', slug: 'tollygunge' },
    ],
  },
  {
    name: 'Pune',
    slug: 'pune',
    state: 'Maharashtra',
    areas: [
      { name: 'Aundh', slug: 'aundh' },
      { name: 'Baner', slug: 'baner' },
      { name: 'Camp', slug: 'camp' },
      { name: 'Hadapsar', slug: 'hadapsar' },
      { name: 'Hinjewadi', slug: 'hinjewadi' },
      { name: 'Kalyani Nagar', slug: 'kalyani-nagar' },
      { name: 'Kharadi', slug: 'kharadi' },
      { name: 'Kothrud', slug: 'kothrud' },
      { name: 'Magarpatta', slug: 'magarpatta' },
      { name: 'Pimpri-Chinchwad', slug: 'pimpri-chinchwad' },
      { name: 'Viman Nagar', slug: 'viman-nagar' },
      { name: 'Wakad', slug: 'wakad' },
    ],
  },
  {
    name: 'Ahmedabad',
    slug: 'ahmedabad',
    state: 'Gujarat',
    areas: [
      { name: 'Ambawadi', slug: 'ambawadi' },
      { name: 'Bopal', slug: 'bopal' },
      { name: 'CG Road', slug: 'cg-road' },
      { name: 'Drive In', slug: 'drive-in' },
      { name: 'Gota', slug: 'gota' },
      { name: 'Maninagar', slug: 'maninagar' },
      { name: 'Navrangpura', slug: 'navrangpura' },
      { name: 'Prahlad Nagar', slug: 'prahlad-nagar' },
      { name: 'Satellite', slug: 'satellite' },
      { name: 'Science City', slug: 'science-city' },
      { name: 'Thaltej', slug: 'thaltej' },
    ],
  },
  {
    name: 'Jaipur',
    slug: 'jaipur',
    state: 'Rajasthan',
    areas: [
      { name: 'C-Scheme', slug: 'c-scheme' },
      { name: 'Civil Lines', slug: 'civil-lines' },
      { name: 'Jagatpura', slug: 'jagatpura' },
      { name: 'Malviya Nagar', slug: 'malviya-nagar' },
      { name: 'Mansarovar', slug: 'mansarovar' },
      { name: 'Sanganer', slug: 'sanganer' },
      { name: 'Tonk Road', slug: 'tonk-road' },
      { name: 'Vaishali Nagar', slug: 'vaishali-nagar' },
    ],
  },
  {
    name: 'Surat',
    slug: 'surat',
    state: 'Gujarat',
    areas: [
      { name: 'Adajan', slug: 'adajan' },
      { name: 'Athwa', slug: 'athwa' },
      { name: 'City Light', slug: 'city-light' },
      { name: 'Katargam', slug: 'katargam' },
      { name: 'Piplod', slug: 'piplod' },
      { name: 'Rander', slug: 'rander' },
      { name: 'Udhna', slug: 'udhna' },
      { name: 'Vesu', slug: 'vesu' },
    ],
  },
  {
    name: 'Lucknow',
    slug: 'lucknow',
    state: 'Uttar Pradesh',
    areas: [
      { name: 'Aliganj', slug: 'aliganj' },
      { name: 'Alambagh', slug: 'alambagh' },
      { name: 'Chowk', slug: 'chowk' },
      { name: 'Gomti Nagar', slug: 'gomti-nagar' },
      { name: 'Hazratganj', slug: 'hazratganj' },
      { name: 'Indira Nagar', slug: 'indira-nagar' },
      { name: 'Rajajipuram', slug: 'rajajipuram' },
      { name: 'Vikas Nagar', slug: 'vikas-nagar' },
    ],
  },
  {
    name: 'Kochi',
    slug: 'kochi',
    state: 'Kerala',
    areas: [
      { name: 'Aluva', slug: 'aluva' },
      { name: 'Ernakulam', slug: 'ernakulam' },
      { name: 'Fort Kochi', slug: 'fort-kochi' },
      { name: 'Kakkanad', slug: 'kakkanad' },
      { name: 'Kalamassery', slug: 'kalamassery' },
      { name: 'MG Road', slug: 'mg-road' },
      { name: 'Palarivattom', slug: 'palarivattom' },
      { name: 'Vyttila', slug: 'vyttila' },
    ],
  },
]

export function getCityBySlug(slug: string): City | undefined {
  return CITIES.find((c) => c.slug === slug)
}

export function getAreaBySlug(citySlug: string, areaSlug: string): Area | undefined {
  const city = getCityBySlug(citySlug)
  return city?.areas.find((a) => a.slug === areaSlug)
}
