export interface Area {
  name: string
  slug: string
}

export interface City {
  name: string
  slug: string
  state: string
  areas: Area[]
}

export const CITIES: City[] = [
  {
    name: 'Mumbai',
    slug: 'mumbai',
    state: 'Maharashtra',
    areas: [
      { name: 'Andheri', slug: 'andheri' },
      { name: 'Bandra', slug: 'bandra' },
      { name: 'Borivali', slug: 'borivali' },
      { name: 'Dadar', slug: 'dadar' },
      { name: 'Goregaon', slug: 'goregaon' },
      { name: 'Juhu', slug: 'juhu' },
      { name: 'Kurla', slug: 'kurla' },
      { name: 'Lower Parel', slug: 'lower-parel' },
      { name: 'Malad', slug: 'malad' },
      { name: 'Mulund', slug: 'mulund' },
      { name: 'Navi Mumbai', slug: 'navi-mumbai' },
      { name: 'Powai', slug: 'powai' },
      { name: 'Thane', slug: 'thane' },
      { name: 'Versova', slug: 'versova' },
      { name: 'Vikhroli', slug: 'vikhroli' },
      { name: 'Worli', slug: 'worli' },
    ],
  },
  {
    name: 'Delhi',
    slug: 'delhi',
    state: 'Delhi',
    areas: [
      { name: 'Connaught Place', slug: 'connaught-place' },
      { name: 'Dwarka', slug: 'dwarka' },
      { name: 'Greater Kailash', slug: 'greater-kailash' },
      { name: 'Janakpuri', slug: 'janakpuri' },
      { name: 'Lajpat Nagar', slug: 'lajpat-nagar' },
      { name: 'Nehru Place', slug: 'nehru-place' },
      { name: 'Pitampura', slug: 'pitampura' },
      { name: 'Preet Vihar', slug: 'preet-vihar' },
      { name: 'Rohini', slug: 'rohini' },
      { name: 'Saket', slug: 'saket' },
      { name: 'Shahdara', slug: 'shahdara' },
      { name: 'South Extension', slug: 'south-extension' },
      { name: 'Vasant Kunj', slug: 'vasant-kunj' },
      { name: 'Noida', slug: 'noida' },
      { name: 'Gurgaon', slug: 'gurgaon' },
      { name: 'Faridabad', slug: 'faridabad' },
    ],
  },
  {
    name: 'Bangalore',
    slug: 'bangalore',
    state: 'Karnataka',
    areas: [
      { name: 'Bellandur', slug: 'bellandur' },
      { name: 'BTM Layout', slug: 'btm-layout' },
      { name: 'Electronic City', slug: 'electronic-city' },
      { name: 'Hebbal', slug: 'hebbal' },
      { name: 'HSR Layout', slug: 'hsr-layout' },
      { name: 'Indiranagar', slug: 'indiranagar' },
      { name: 'Jayanagar', slug: 'jayanagar' },
      { name: 'JP Nagar', slug: 'jp-nagar' },
      { name: 'Koramangala', slug: 'koramangala' },
      { name: 'Malleswaram', slug: 'malleswaram' },
      { name: 'Marathahalli', slug: 'marathahalli' },
      { name: 'Rajajinagar', slug: 'rajajinagar' },
      { name: 'Sarjapur Road', slug: 'sarjapur-road' },
      { name: 'Whitefield', slug: 'whitefield' },
      { name: 'Yelahanka', slug: 'yelahanka' },
      { name: 'Yeshwanthpur', slug: 'yeshwanthpur' },
    ],
  },
  {
    name: 'Hyderabad',
    slug: 'hyderabad',
    state: 'Telangana',
    areas: [
      { name: 'Ameerpet', slug: 'ameerpet' },
      { name: 'Banjara Hills', slug: 'banjara-hills' },
      { name: 'Charminar', slug: 'charminar' },
      { name: 'Gachibowli', slug: 'gachibowli' },
      { name: 'Hi-Tech City', slug: 'hitech-city' },
      { name: 'Jubilee Hills', slug: 'jubilee-hills' },
      { name: 'Kondapur', slug: 'kondapur' },
      { name: 'Kukatpally', slug: 'kukatpally' },
      { name: 'LB Nagar', slug: 'lb-nagar' },
      { name: 'Madhapur', slug: 'madhapur' },
      { name: 'Malkajgiri', slug: 'malkajgiri' },
      { name: 'Miyapur', slug: 'miyapur' },
      { name: 'Secunderabad', slug: 'secunderabad' },
      { name: 'Uppal', slug: 'uppal' },
    ],
  },
  {
    name: 'Chennai',
    slug: 'chennai',
    state: 'Tamil Nadu',
    areas: [
      { name: 'Adyar', slug: 'adyar' },
      { name: 'Anna Nagar', slug: 'anna-nagar' },
      { name: 'Chrompet', slug: 'chrompet' },
      { name: 'Guindy', slug: 'guindy' },
      { name: 'Kilpauk', slug: 'kilpauk' },
      { name: 'Kodambakkam', slug: 'kodambakkam' },
      { name: 'Mylapore', slug: 'mylapore' },
      { name: 'Nungambakkam', slug: 'nungambakkam' },
      { name: 'OMR', slug: 'omr' },
      { name: 'Perambur', slug: 'perambur' },
      { name: 'Porur', slug: 'porur' },
      { name: 'T Nagar', slug: 't-nagar' },
      { name: 'Tambaram', slug: 'tambaram' },
      { name: 'Velachery', slug: 'velachery' },
    ],
  },
  {
    name: 'Kolkata',
    slug: 'kolkata',
    state: 'West Bengal',
    areas: [
      { name: 'Ballygunge', slug: 'ballygunge' },
      { name: 'Behala', slug: 'behala' },
      { name: 'Dum Dum', slug: 'dum-dum' },
      { name: 'Howrah', slug: 'howrah' },
      { name: 'Jadavpur', slug: 'jadavpur' },
      { name: 'Lake Town', slug: 'lake-town' },
      { name: 'New Town', slug: 'new-town' },
      { name: 'Park Street', slug: 'park-street' },
      { name: 'Salt Lake', slug: 'salt-lake' },
      { name: 'Tollygunge', slug: 'tollygunge' },
    ],
  },
  {
    name: 'Pune',
    slug: 'pune',
    state: 'Maharashtra',
    areas: [
      { name: 'Aundh', slug: 'aundh' },
      { name: 'Baner', slug: 'baner' },
      { name: 'Camp', slug: 'camp' },
      { name: 'Hadapsar', slug: 'hadapsar' },
      { name: 'Hinjewadi', slug: 'hinjewadi' },
      { name: 'Kalyani Nagar', slug: 'kalyani-nagar' },
      { name: 'Kharadi', slug: 'kharadi' },
      { name: 'Kothrud', slug: 'kothrud' },
      { name: 'Magarpatta', slug: 'magarpatta' },
      { name: 'Pimpri-Chinchwad', slug: 'pimpri-chinchwad' },
      { name: 'Viman Nagar', slug: 'viman-nagar' },
      { name: 'Wakad', slug: 'wakad' },
    ],
  },
  {
    name: 'Ahmedabad',
    slug: 'ahmedabad',
    state: 'Gujarat',
    areas: [
      { name: 'Ambawadi', slug: 'ambawadi' },
      { name: 'Bopal', slug: 'bopal' },
      { name: 'CG Road', slug: 'cg-road' },
      { name: 'Drive In', slug: 'drive-in' },
      { name: 'Gota', slug: 'gota' },
      { name: 'Maninagar', slug: 'maninagar' },
      { name: 'Navrangpura', slug: 'navrangpura' },
      { name: 'Prahlad Nagar', slug: 'prahlad-nagar' },
      { name: 'Satellite', slug: 'satellite' },
      { name: 'Science City', slug: 'science-city' },
      { name: 'Thaltej', slug: 'thaltej' },
    ],
  },
  {
    name: 'Jaipur',
    slug: 'jaipur',
    state: 'Rajasthan',
    areas: [
      { name: 'C-Scheme', slug: 'c-scheme' },
      { name: 'Civil Lines', slug: 'civil-lines' },
      { name: 'Jagatpura', slug: 'jagatpura' },
      { name: 'Malviya Nagar', slug: 'malviya-nagar' },
      { name: 'Mansarovar', slug: 'mansarovar' },
      { name: 'Sanganer', slug: 'sanganer' },
      { name: 'Tonk Road', slug: 'tonk-road' },
      { name: 'Vaishali Nagar', slug: 'vaishali-nagar' },
    ],
  },
  {
    name: 'Surat',
    slug: 'surat',
    state: 'Gujarat',
    areas: [
      { name: 'Adajan', slug: 'adajan' },
      { name: 'Athwa', slug: 'athwa' },
      { name: 'City Light', slug: 'city-light' },
      { name: 'Katargam', slug: 'katargam' },
      { name: 'Piplod', slug: 'piplod' },
      { name: 'Rander', slug: 'rander' },
      { name: 'Udhna', slug: 'udhna' },
      { name: 'Vesu', slug: 'vesu' },
    ],
  },
  {
    name: 'Lucknow',
    slug: 'lucknow',
    state: 'Uttar Pradesh',
    areas: [
      { name: 'Aliganj', slug: 'aliganj' },
      { name: 'Alambagh', slug: 'alambagh' },
      { name: 'Chowk', slug: 'chowk' },
      { name: 'Gomti Nagar', slug: 'gomti-nagar' },
      { name: 'Hazratganj', slug: 'hazratganj' },
      { name: 'Indira Nagar', slug: 'indira-nagar' },
      { name: 'Rajajipuram', slug: 'rajajipuram' },
      { name: 'Vikas Nagar', slug: 'vikas-nagar' },
    ],
  },
  {
    name: 'Kochi',
    slug: 'kochi',
    state: 'Kerala',
    areas: [
      { name: 'Aluva', slug: 'aluva' },
      { name: 'Ernakulam', slug: 'ernakulam' },
      { name: 'Fort Kochi', slug: 'fort-kochi' },
      { name: 'Kakkanad', slug: 'kakkanad' },
      { name: 'Kalamassery', slug: 'kalamassery' },
      { name: 'MG Road', slug: 'mg-road' },
      { name: 'Palarivattom', slug: 'palarivattom' },
      { name: 'Vyttila', slug: 'vyttila' },
    ],
  },
  {
    name: 'Nagpur',
    slug: 'nagpur',
    state: 'Maharashtra',
    areas: [
      { name: 'Civil Lines', slug: 'civil-lines' },
      { name: 'Dharampeth', slug: 'dharampeth' },
      { name: 'Hingna', slug: 'hingna' },
      { name: 'Manish Nagar', slug: 'manish-nagar' },
      { name: 'Pratap Nagar', slug: 'pratap-nagar' },
      { name: 'Sadar', slug: 'sadar' },
      { name: 'Sitabuldi', slug: 'sitabuldi' },
      { name: 'Wardha Road', slug: 'wardha-road' },
    ],
  },
  {
    name: 'Indore',
    slug: 'indore',
    state: 'Madhya Pradesh',
    areas: [
      { name: 'AB Road', slug: 'ab-road' },
      { name: 'Bhawarkua', slug: 'bhawarkua' },
      { name: 'Palasia', slug: 'palasia' },
      { name: 'Rajendra Nagar', slug: 'rajendra-nagar' },
      { name: 'Saket', slug: 'saket' },
      { name: 'Vijay Nagar', slug: 'vijay-nagar' },
    ],
  },
  {
    name: 'Bhopal',
    slug: 'bhopal',
    state: 'Madhya Pradesh',
    areas: [
      { name: 'Arera Colony', slug: 'arera-colony' },
      { name: 'Bairagarh', slug: 'bairagarh' },
      { name: 'Bittan Market', slug: 'bittan-market' },
      { name: 'Habibganj', slug: 'habibganj' },
      { name: 'Kolar Road', slug: 'kolar-road' },
      { name: 'MP Nagar', slug: 'mp-nagar' },
    ],
  },
  {
    name: 'Patna',
    slug: 'patna',
    state: 'Bihar',
    areas: [
      { name: 'Bailey Road', slug: 'bailey-road' },
      { name: 'Boring Road', slug: 'boring-road' },
      { name: 'Danapur', slug: 'danapur' },
      { name: 'Frazer Road', slug: 'frazer-road' },
      { name: 'Kankarbagh', slug: 'kankarbagh' },
      { name: 'Patliputra', slug: 'patliputra' },
    ],
  },
  {
    name: 'Vadodara',
    slug: 'vadodara',
    state: 'Gujarat',
    areas: [
      { name: 'Akota', slug: 'akota' },
      { name: 'Alkapuri', slug: 'alkapuri' },
      { name: 'Fatehgunj', slug: 'fatehgunj' },
      { name: 'Gotri', slug: 'gotri' },
      { name: 'Manjalpur', slug: 'manjalpur' },
      { name: 'Sayajigunj', slug: 'sayajigunj' },
    ],
  },
  {
    name: 'Coimbatore',
    slug: 'coimbatore',
    state: 'Tamil Nadu',
    areas: [
      { name: 'Avinashi Road', slug: 'avinashi-road' },
      { name: 'Gandhipuram', slug: 'gandhipuram' },
      { name: 'Peelamedu', slug: 'peelamedu' },
      { name: 'RS Puram', slug: 'rs-puram' },
      { name: 'Saibaba Colony', slug: 'saibaba-colony' },
      { name: 'Singanallur', slug: 'singanallur' },
    ],
  },
  {
    name: 'Visakhapatnam',
    slug: 'visakhapatnam',
    state: 'Andhra Pradesh',
    areas: [
      { name: 'Beach Road', slug: 'beach-road' },
      { name: 'Dwaraka Nagar', slug: 'dwaraka-nagar' },
      { name: 'Gajuwaka', slug: 'gajuwaka' },
      { name: 'MVP Colony', slug: 'mvp-colony' },
      { name: 'Madhurawada', slug: 'madhurawada' },
      { name: 'Siripuram', slug: 'siripuram' },
    ],
  },
  {
    name: 'Chandigarh',
    slug: 'chandigarh',
    state: 'Chandigarh',
    areas: [
      { name: 'Industrial Area', slug: 'industrial-area' },
      { name: 'Manimajra', slug: 'manimajra' },
      { name: 'Mohali', slug: 'mohali' },
      { name: 'Panchkula', slug: 'panchkula' },
      { name: 'Sector 17', slug: 'sector-17' },
      { name: 'Sector 22', slug: 'sector-22' },
      { name: 'Sector 35', slug: 'sector-35' },
      { name: 'Zirakpur', slug: 'zirakpur' },
    ],
  },
  {
    name: 'Goa',
    slug: 'goa',
    state: 'Goa',
    areas: [
      { name: 'Anjuna', slug: 'anjuna' },
      { name: 'Baga', slug: 'baga' },
      { name: 'Calangute', slug: 'calangute' },
      { name: 'Candolim', slug: 'candolim' },
      { name: 'Margao', slug: 'margao' },
      { name: 'Panaji', slug: 'panaji' },
      { name: 'Vasco da Gama', slug: 'vasco-da-gama' },
    ],
  },
  {
    name: 'Guwahati',
    slug: 'guwahati',
    state: 'Assam',
    areas: [
      { name: 'Beltola', slug: 'beltola' },
      { name: 'Dispur', slug: 'dispur' },
      { name: 'Fancy Bazar', slug: 'fancy-bazar' },
      { name: 'GS Road', slug: 'gs-road' },
      { name: 'Paltan Bazar', slug: 'paltan-bazar' },
      { name: 'Six Mile', slug: 'six-mile' },
    ],
  },
  {
    name: 'Bhubaneswar',
    slug: 'bhubaneswar',
    state: 'Odisha',
    areas: [
      { name: 'Chandrasekharpur', slug: 'chandrasekharpur' },
      { name: 'Jayadev Vihar', slug: 'jayadev-vihar' },
      { name: 'Khandagiri', slug: 'khandagiri' },
      { name: 'Nayapalli', slug: 'nayapalli' },
      { name: 'Patia', slug: 'patia' },
      { name: 'Saheed Nagar', slug: 'saheed-nagar' },
    ],
  },
  {
    name: 'Mysore',
    slug: 'mysore',
    state: 'Karnataka',
    areas: [
      { name: 'Gokulam', slug: 'gokulam' },
      { name: 'Hebbal', slug: 'hebbal' },
      { name: 'Jayanagar', slug: 'jayanagar' },
      { name: 'Kuvempunagar', slug: 'kuvempunagar' },
      { name: 'Saraswathipuram', slug: 'saraswathipuram' },
      { name: 'Vijayanagar', slug: 'vijayanagar' },
    ],
  },
  {
    name: 'Nashik',
    slug: 'nashik',
    state: 'Maharashtra',
    areas: [
      { name: 'Cidco', slug: 'cidco' },
      { name: 'College Road', slug: 'college-road' },
      { name: 'Deolali', slug: 'deolali' },
      { name: 'Gangapur Road', slug: 'gangapur-road' },
      { name: 'Indira Nagar', slug: 'indira-nagar' },
      { name: 'Panchavati', slug: 'panchavati' },
    ],
  },
  {
    name: 'Mangalore',
    slug: 'mangalore',
    state: 'Karnataka',
    areas: [
      { name: 'Balmatta', slug: 'balmatta' },
      { name: 'Bejai', slug: 'bejai' },
      { name: 'Bendoorwell', slug: 'bendoorwell' },
      { name: 'Hampankatta', slug: 'hampankatta' },
      { name: 'Kadri', slug: 'kadri' },
      { name: 'Kankanady', slug: 'kankanady' },
    ],
  },
  {
    name: 'Vijayawada',
    slug: 'vijayawada',
    state: 'Andhra Pradesh',
    areas: [
      { name: 'Benz Circle', slug: 'benz-circle' },
      { name: 'Governorpet', slug: 'governorpet' },
      { name: 'Labbipet', slug: 'labbipet' },
      { name: 'MG Road', slug: 'mg-road' },
      { name: 'Patamata', slug: 'patamata' },
      { name: 'Tadepalli', slug: 'tadepalli' },
    ],
  },
  {
    name: 'Kanpur',
    slug: 'kanpur',
    state: 'Uttar Pradesh',
    areas: [
      { name: 'Civil Lines', slug: 'civil-lines' },
      { name: 'Govind Nagar', slug: 'govind-nagar' },
      { name: 'Kakadeo', slug: 'kakadeo' },
      { name: 'Kidwai Nagar', slug: 'kidwai-nagar' },
      { name: 'Mall Road', slug: 'mall-road' },
      { name: 'Swaroop Nagar', slug: 'swaroop-nagar' },
    ],
  },
  {
    name: 'Agra',
    slug: 'agra',
    state: 'Uttar Pradesh',
    areas: [
      { name: 'Civil Lines', slug: 'civil-lines' },
      { name: 'Dayalbagh', slug: 'dayalbagh' },
      { name: 'Kamla Nagar', slug: 'kamla-nagar' },
      { name: 'Sadar Bazaar', slug: 'sadar-bazaar' },
      { name: 'Sanjay Place', slug: 'sanjay-place' },
      { name: 'Tajganj', slug: 'tajganj' },
    ],
  },
  {
    name: 'Varanasi',
    slug: 'varanasi',
    state: 'Uttar Pradesh',
    areas: [
      { name: 'Bhelupur', slug: 'bhelupur' },
      { name: 'Cantt', slug: 'cantt' },
      { name: 'Lanka', slug: 'lanka' },
      { name: 'Mahmoorganj', slug: 'mahmoorganj' },
      { name: 'Sigra', slug: 'sigra' },
      { name: 'Sundarpur', slug: 'sundarpur' },
    ],
  },
  {
    name: 'Ranchi',
    slug: 'ranchi',
    state: 'Jharkhand',
    areas: [
      { name: 'Ashok Nagar', slug: 'ashok-nagar' },
      { name: 'Doranda', slug: 'doranda' },
      { name: 'Hinoo', slug: 'hinoo' },
      { name: 'Kanke Road', slug: 'kanke-road' },
      { name: 'Lalpur', slug: 'lalpur' },
      { name: 'Main Road', slug: 'main-road' },
    ],
  },
  {
    name: 'Raipur',
    slug: 'raipur',
    state: 'Chhattisgarh',
    areas: [
      { name: 'Civil Lines', slug: 'civil-lines' },
      { name: 'Devendra Nagar', slug: 'devendra-nagar' },
      { name: 'Pandri', slug: 'pandri' },
      { name: 'Shankar Nagar', slug: 'shankar-nagar' },
      { name: 'Tatibandh', slug: 'tatibandh' },
      { name: 'VIP Road', slug: 'vip-road' },
    ],
  },
  {
    name: 'Dehradun',
    slug: 'dehradun',
    state: 'Uttarakhand',
    areas: [
      { name: 'Clement Town', slug: 'clement-town' },
      { name: 'Dalanwala', slug: 'dalanwala' },
      { name: 'Race Course', slug: 'race-course' },
      { name: 'Rajpur Road', slug: 'rajpur-road' },
      { name: 'Sahastradhara Road', slug: 'sahastradhara-road' },
      { name: 'Vasant Vihar', slug: 'vasant-vihar' },
    ],
  },
  {
    name: 'Amritsar',
    slug: 'amritsar',
    state: 'Punjab',
    areas: [
      { name: 'Hall Bazaar', slug: 'hall-bazaar' },
      { name: 'Lawrence Road', slug: 'lawrence-road' },
      { name: 'Mall Road', slug: 'mall-road' },
      { name: 'Putlighar', slug: 'putlighar' },
      { name: 'Ranjit Avenue', slug: 'ranjit-avenue' },
    ],
  },
  {
    name: 'Ludhiana',
    slug: 'ludhiana',
    state: 'Punjab',
    areas: [
      { name: 'Civil Lines', slug: 'civil-lines' },
      { name: 'Dugri', slug: 'dugri' },
      { name: 'Ferozepur Road', slug: 'ferozepur-road' },
      { name: 'Model Town', slug: 'model-town' },
      { name: 'Sarabha Nagar', slug: 'sarabha-nagar' },
    ],
  },
  {
    name: 'Madurai',
    slug: 'madurai',
    state: 'Tamil Nadu',
    areas: [
      { name: 'Anna Nagar', slug: 'anna-nagar' },
      { name: 'Goripalayam', slug: 'goripalayam' },
      { name: 'KK Nagar', slug: 'kk-nagar' },
      { name: 'Mattuthavani', slug: 'mattuthavani' },
      { name: 'Tallakulam', slug: 'tallakulam' },
    ],
  },
  {
    name: 'Trivandrum',
    slug: 'trivandrum',
    state: 'Kerala',
    areas: [
      { name: 'Kazhakkoottam', slug: 'kazhakkoottam' },
      { name: 'Kowdiar', slug: 'kowdiar' },
      { name: 'Pattom', slug: 'pattom' },
      { name: 'Sasthamangalam', slug: 'sasthamangalam' },
      { name: 'Technopark', slug: 'technopark' },
      { name: 'Vellayambalam', slug: 'vellayambalam' },
    ],
  },
  {
    name: 'Aurangabad',
    slug: 'aurangabad',
    state: 'Maharashtra',
    areas: [
      { name: 'Cidco', slug: 'cidco' },
      { name: 'Garkheda', slug: 'garkheda' },
      { name: 'Jalna Road', slug: 'jalna-road' },
      { name: 'Osmanpura', slug: 'osmanpura' },
      { name: 'Samarth Nagar', slug: 'samarth-nagar' },
    ],
  },
  {
    name: 'Rajkot',
    slug: 'rajkot',
    state: 'Gujarat',
    areas: [
      { name: 'Kalawad Road', slug: 'kalawad-road' },
      { name: 'Mavdi', slug: 'mavdi' },
      { name: 'Race Course', slug: 'race-course' },
      { name: 'University Road', slug: 'university-road' },
      { name: 'Yagnik Road', slug: 'yagnik-road' },
    ],
  },
]

export function getCityBySlug(slug: string): City | undefined {
  return CITIES.find((c) => c.slug === slug)
}

export function getAreaBySlug(citySlug: string, areaSlug: string): Area | undefined {
  const city = getCityBySlug(citySlug)
  return city?.areas.find((a) => a.slug === areaSlug)
}
